name: simpletimer
description: A timer.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.5
  platform_info: ^3.2.0
  getwidget: ^3.0.1
  json_annotation: ^4.7.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/config.json